### ISSUE TITLE
Extension not starting

### ISSUE THREAD

**Issue by david2928** [aalteirac/mdemo#2]
Hi,

The tool looks great, but I dont get it started.

Zipped the file from github, unzipped, renamed, moved to C:\Program Files\Qlik\Sense\Client\mdemo
and opened /resources/mdemo/index.html, but getting this error:

![image](https://cloud.githubusercontent.com/assets/22662488/19156657/e66a691a-8c0c-11e6-8b07-d76dcd673c6a.png)

Any ideas?

Thanks,
David

**Comment by aalteirac** [comment]
Hi, what's your chrome version and Qlik Sense version ? Could you expand the error from the console to show the full stack ? Does it work on Desktop and fail only on server ?
Thanks

**Comment by david2928** [comment]
Thanks for the quick reply.

Running Qlik Sense 3.1 and Chrome 53.0.2785.143.

Error can not be expanded :(

**Comment by david2928** [comment]
Also tried Edge and same issue.

**Comment by aalteirac** [comment]
Ok, I can reproduce, CORS issue on the html template. Will be fixed soon

**Comment by aalteirac** [comment]
Could you give it a try now, just get and replace the mdemo2.0.js file, be sure to clear the cache :-)

**Comment by david2928** [comment]
Amazing, works now! Thanks a lot :)
