### ISSUE TITLE
Index page just displays "introuvable"

### ISSUE THREAD

**Issue by Mustaoha** [aalteirac/mdemo#3]
hi there,
im very interesting to try this awesom tool.
i did download (only found "mdemo-master" and not xxxx.mdemo"
i renamed it to "mdemo" and put this renamed zip file to 
c:\program File\qlik\sense\client

when loading the Index page
https://localhost/resources/mdemo/index.html  directly on Qlik sense server, i have a blanck page with only a word "Introuvable"

Could you help please?
maybe didnt download Server version...

Many thanks

**Comment by aalteirac** [comment]
Hi Mustaoha, 

did you restart your server ? What's the version ?

Thanks

**Comment by Mustaoha** [comment]
Hi,
it was the SR2, and not i didn't restart the server.
since your message i have rebooted the server => same pb
uninstalled SR2 and installed SR1..same pb ;-(

**Comment by aalteirac** [comment]
Did you unzip the archive ?

**Comment by Mustaoha** [comment]
since i had a doubt i have tried both ;-)
once with the content of the zip file (Put the Folder into right place)
once with the zip file itself (Put the ZIPinto right place)
thanks for following

**Comment by aalteirac** [comment]
You need to unzip, then the resulting folder must be renamed to mdemo and put in /client

**Comment by Mustaoha** [comment]
I did it... 
is it normal the Index.html file contains URL:  
//localhost:4848/resources/assets/client/client.css

Do i have to edit them manually ...since this URL coudn't work with Server version (vs desktop version)

**Comment by aalteirac** [comment]
You should have something different than a 404, for the moment it means the html is not found which is super weird

**Comment by Mustaoha** [comment]
what kind of test can i do ?
I mean is there any file i can launch manually in order to troubleshoot...ie: if i launch the index.html , should i see anything (that's not the case, blank page)

**Comment by aalteirac** [comment]
If running chrome, press f12 and have a look on the network tab. Send a screenshot

**Comment by aalteirac** [comment]
Ensure you have the following in terms of installation: 
![install](https://cloud.githubusercontent.com/assets/8478296/20846159/a07f6f20-b8c8-11e6-977e-aa416f6c7e84.png)

**Comment by Mustaoha** [comment]
![mdemo](https://cloud.githubusercontent.com/assets/24248491/20846500/3cb112da-b8ca-11e6-9d86-2627eaca754c.PNG)

**Comment by Mustaoha** [comment]
rebooted again server since SR1 install :-)
![mdemo](https://cloud.githubusercontent.com/assets/24248491/20846899/131ef3fe-b8cc-11e6-8f32-aa55e5f5eea5.PNG)

MANY THANKS for you assistance

**Comment by aalteirac** [comment]
Great ! Any chance to check if it was SR2 issue or just an install problem ? Many thanks

**Comment by Mustaoha** [comment]
Even i Loooove you for your help; i will not retry install on the SR2 ;-)
The server i m using is server we=here we install Mnay many trials (i know that 's better to have dedicated machine, but you know...)

Have a great evening
ps: i had a quick look on it since it works, if you are author of this App...let me call you KING !

**Comment by aalteirac** [comment]
No worries :-), I will test SR2 on my own. 
I'm the king of dirty code, for sure...

**Comment by Mustaoha** [comment]
I would like to do "dirty code" like that !
is there any guide ?
i just did a dummy marsup on the server, how can i open the "web site" (mashup) i just created on another computer ... i mean open this mashup only and note the whole app...ark even for me my sentense is not clear.
do you speak french ?

**Comment by aalteirac** [comment]
I suggest you to visit the help site, there's plenty of samples. The dev-hub is also super helpful: localhost/dev-hub
Have fun !
