### ISSUE TITLE
Template "elegant" doesn't work

### ISSUE THREAD

**Issue by paulcalvet** [aalteirac/mdemo#4]
Hi Anthony,

When I select the elegant template, Qlik objects don't appear on the mashup.
Do you have the same problem ?

Your extension is really great !
Thanks,

Paul Calvet

**Comment by aalteirac** [comment]
Hi Paul, it should be fixed now. Empty your cache to avoid any problem. Let me know.

Thanks !

**Comment by paulcalvet** [comment]
Thanks Anthony, That's works now :-)

**Comment by aalteirac** [comment]
Please recheckout as I discovered some other problems meanwhile. Should be fine now :-)

**Comment by paulcalvet** [comment]
Hi Anthony,
It looks fine with the last version.
Thanks for your work.

Paul
