### ISSUE TITLE
mdemo tested in 3.2 yet

### ISSUE THREAD

**Issue by mhr2015** [aalteirac/mdemo#5]
Hi Anthony,

when using mdemo in 3.2 (preview), I have trouble signing in (server) or retrieving the list of apps (desktop 3.2). is this a tested scenario yet? Merci

![image](https://cloud.githubusercontent.com/assets/15238912/22472456/fae8835c-e7d5-11e6-98c7-0b73c3e97bea.png)

**Comment by aalteirac** [comment]
Hi mhr2015, 

It should be ok now, could you let me know ?

Thanks !

**Comment by aalteirac** [comment]
Fixed, tested on 3.2 preview desktop and server
