### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by srickman** [aalteirac/mdemo#7]
Hi all,

I'm using this on Qlik Sense server, and have gone through the installation and followed the below steps:

- Download the zip and deploy in
- C:\Program Files\Qlik\Sense\Client
- RENAME the folder ( the zip name contains the branch name...):
- From "xxxx.mdemo-....." --> to "mdemo"
- Open a browser: 
- http(s)://my_senseserver/resources/mdemo/index.html

I open up the link above in my chrome browser, and get the below error each time I select the app. If I hit refresh it just refreshes (obviously). And if I hit done nothing happens.
Thanks in advance
![image](https://user-images.githubusercontent.com/34286554/33631546-c7788592-da02-11e7-9ead-4822309a287a.png)

**Comment by aalteirac** [comment]
Sorry for late answer srickman, for unknown reason my notification was deactivated :-/
it's solved, could you confirm ?

**Comment by lucianopw** [comment]
I'm having the same problem on Qlik Sense Server.

**Comment by aalteirac** [comment]
Hi Luciano, did you download the latest ? What's the server version ?
Will be great if you can also test on desktop.
Many thanks !

**Comment by srickman** [comment]
Hi. Sorry for delay. Still having the same issue yes. I'll get the version info.

**Comment by lucianopw** [comment]
Hello @aalteirac , thanks for answering. I downloaded the latest version available. I'm using Qlik Sense Server version November 2017. In Qlik Sense Desktop works perfectly.

**Comment by aalteirac** [comment]
oki, good start :-) Did you have an old version running before on this server ? If so you probably need to clear cache in your browser (or try from another machine or try in incognito mode).

**Comment by lucianopw** [comment]
I have not had previous versions. I cleared my browser's full cache and it's still not connected.

**Comment by lucianopw** [comment]
Excuse my English, I'm using a translator.

**Comment by aalteirac** [comment]
thanks Luciano ! I need to setup a box with Nov release and retest. I'll do my best to come back asap. Just to confirm, when you open the page it's all good, when you select an app you have a popup saying 'connection lost', correct ?

**Comment by lucianopw** [comment]
Thanks in advance.
The error happens when I open the page, I can not select the applications, that is, it does not connect.
![image](https://user-images.githubusercontent.com/14374060/35337791-75ff48ec-00f2-11e8-894c-f67c422c8b2f.png)
![image](https://user-images.githubusercontent.com/14374060/35337968-061a6844-00f3-11e8-8139-1a22c6cfb5cf.png)

**Comment by aalteirac** [comment]
Ok so I can reproduce the issue, which doesn't occur in future releases, hopefully... It is more serious than I was thinking so will require a bit of extra time to ensure it will be fixed for Nov + next ones. 
Stay tuned, I'll do my best ;-)

**Comment by aalteirac** [comment]
Luciano, srickman, 

I have tested on Nov + next and it sounds OK for me now. Please take the latest, clear cache and let me know it's doing the job also for you.

Many thanks !!!

**Comment by srickman** [comment]
Thanks Anthony. If possible can you send a link to the latest Nov +?

**Comment by lucianopw** [comment]
@aalteirac , it worked perfectly. Thank you very much for sharing your knowledge.

**Comment by aalteirac** [comment]
srickman, just use the normal way to get your server install package (you should have an enterprise account) or just play with Desktop, it's free, just go to qlik.com :-)

Does it means it still doesn't work for you ? What's your server version ?

**Comment by lucianopw** [comment]
@aalteirac , is there any way to insert objects from different applications?

**Comment by lucianopw** [comment]
@aalteirac , is there any way to insert objects from different applications?

**Comment by aalteirac** [comment]
Hi Luciano, no it's not possible in this solution, technically feasible with mashups but not in that one. It's mainly to demonstrate the power of Qlik api's, not a production tool.

**Comment by aalteirac** [comment]
I'll close the issue as it sounds fixed, @srickman let me know if it still doesn't work for you and I'll be happy to reopen.

Many thanks both !
