### ISSUE TITLE
Not working in Sense Desktop June 2018 release

### ISSUE THREAD

**Issue by imtiazu** [aalteirac/mdemo#8]
Get the below errors in Chrome... 

![image](https://user-images.githubusercontent.com/11614992/42523153-2ec4efd2-846d-11e8-898f-ab161d61d555.png)

**Comment by michel74100** [comment]
Hi,

At the beginning, it was not working for me. But you have to copy index.html to mdemo.qextindex.html

and go in (QMC) QlikSense Management Console. Go to Mashup. Then open folder Mdemo and click on View

After it, you could use the normal link with index.html

**Comment by imtiazu** [comment]
No that doesn’t work for me.

**Comment by caspervanpomeren** [comment]
Did you ever get this to work?

**Comment by aalteirac** [comment]
Hey guys, sorry this repo is pretty old, has been created for Sense 1.0 :-)
Just publish a quick fix to get this back to life, some templates are still broken, but some work well... 
Not a lot of time to maintain it so if someone interested to take ownership, ping me !
Download the latest, clear you cache and let me know. Tx !

**Comment by caspervanpomeren** [comment]
Hi @aalteirac , no worries, I knew the repo was pretty old and didn't really expect you to maintain it for years. It's a good demo though and is nice to use for inspiration.

Might use this as a basis for a demo 2.0, but currently a bit busy. If I ever do find the time, i'll let you know.

Thanks for the quick fix.

**Comment by aalteirac** [comment]
Just fixed the mashboard template, will have a look over the weekend to fix:
- lightboard template (some chart are not showing correctly)
- left panel, tab labels buggy

Out of that it seems fine :-) not that bad for such a messy and old code :-)
Let me know if you see more issues
Tx

**Comment by lohansen** [comment]
Hi there,
Your demo mashup looks really powerful and I made it work in Sense Desktop Nov 2018 release. However, I cannot make it work in Sense Server. I followed the instructions but just get an error in Chrome saying 'The requested resource cannot be found'
I can see the extension in the QMC and also the Mashup 'MDemo' in the Devhhub under Mashups, but same error when opening.
Can you help?

**Comment by aalteirac** [comment]
Hi Iohansen, you shouldn't see the extension in QMC. For server it's not an extension, just static content deployed and behind the Sense proxy:
FOR QLIK SENSE SERVER

Download the zip and deploy in

**C:\Program Files\Qlik\Sense\Client**

Then you navigate to http(s)://my_senseserver/**resources/mdemo/index.html**

Hope it helps

**Comment by lohansen** [comment]
Hi Anthony,

Thanks for a swift response.

I thought I had done as described, but perhaps I misunderstand ‘deploy in C:\Program Files\Qlik\Sense\Client’. I basically unzipped it there.

But how will Qlik Sense know is is now a’ressource’ according to the url below?

http(s)://my_senseserver/resources/mdemo/index.html

I now have an mdemo folder under ‘Client’ and this is where the index.html resides.

Can you confirm based on the screenshot below that I have done it right? (this in on the Qlik server)

[cid:image001.png@01D4BA2D.CE683EE0]

Best regards

LARS OLE HANSEN
Product Manager, Director
PAR Product Management DK


[cid:image002.png@01D4BA2D.CE683EE0]<http://www.simcorp.com/>
ONE SYSTEM FOR A COMPLEX WORLD

SimCorp A/S
Weidekampsgade 16, 2300 Copenhagen S, Denmark
Mobile: +45 22 23 47 92 · Phone: +45 3544 8800 · Direct: +45 3544 6434
Lars.O.Hansen@simcorp.com<mailto:Lars.O.Hansen@simcorp.com> · www.simcorp.com<http://www.simcorp.com/>

Company reg. no. 15505281

[cid:image003.png@01D4BA2D.CE683EE0]<https://www.linkedin.com/company/simcorp> [cid:image004.png@01D4BA2D.CE683EE0] <https://www.facebook.com/pages/SimCorp/137969019578871?fref=ts>  [cid:image005.png@01D4BA2D.CE683EE0] <https://twitter.com/simcorp>  [cid:image006.png@01D4BA2D.CE683EE0] <https://www.youtube.com/user/SimCorpTV>

**Comment by rasmusgadensgaard** [comment]
@lohansen 

You need to install it via the "extension" menu point in the QMC. Afterwards it will be accessible on http(s)://my_senseserver/resources/mdemo/index.html just like any other mashup.

**Comment by lohansen** [comment]
Thanks! It works now. Great tool

/Lars Ole

**Comment by aalteirac** [comment]
> @lohansen
> 
> You need to install it via the "extension" menu point in the QMC. Afterwards it will be accessible on http(s)://my_senseserver/resources/mdemo/index.html just like any other mashup.

Hey Rasmus, that's not really exact, if deployed as extension in QMC you'll need to go to ../extensions/mdemo/index.html. If unzipped in ../Sense/Client you'll use ../resources/mdemo/index.html

Everything in ../Sense/Client is served by the proxy. I can't remember why I did that but I've never tested it if deployed as extension on Sense Server... Probably some relative paths can be broken.

**Comment by aalteirac** [comment]
Closed :-)
